-- Revert schemas/dashboard_public/tables/object_type_attribute_language_variations/triggers/peoplestamps from pg

BEGIN;

ALTER TABLE dashboard_public.object_type_attribute_language_variations DROP COLUMN created_by;
ALTER TABLE dashboard_public.object_type_attribute_language_variations DROP COLUMN updated_by;
DROP TRIGGER update_object_type_attribute_language_variations_moduser ON dashboard_public.object_type_attribute_language_variations;

COMMIT;
