-- Revert dashboard:schemas/dashboard_public/tables/form_question_language_variations/alterations/form_question_language_variations_lang_code_chk from pg

BEGIN;

ALTER TABLE dashboard_public.form_question_language_variations DROP CONSTRAINT form_question_language_variations_lang_code_chk;

COMMIT;
