-- Revert: schemas/dashboard_public/tables/organization_profile_variations/triggers/organization_profile_variations_organization_id_immutable_tg from pg

BEGIN;
DROP TRIGGER organization_profile_variations_organization_id_immutable_tg ON "dashboard_public".organization_profile_variations;
COMMIT;  

