-- Revert: schemas/dashboard_public/tables/question_template_language_variations/constraints/question_template_language_variations_question_template_id_fkey/alterations/alt0000001453 from pg

BEGIN;
COMMENT ON CONSTRAINT question_template_language_variations_question_template_id_fkey ON "dashboard_public".question_template_language_variations IS NULL;
COMMIT;  

