-- Revert: schemas/dashboard_public/tables/question_value_language_variations/constraints/question_value_language_variations_question_value_id_lang_code_/alterations/alt0000001446 from pg

BEGIN;
COMMENT ON CONSTRAINT question_value_language_variations_question_value_id_lang_code_ ON "dashboard_public".question_value_language_variations IS NULL;
COMMIT;  

