-- Revert schemas/dashboard_public/tables/user_dismissed_track_actions/triggers/user_dismissed_track_actions_track_action_id_immutable_tg from pg

BEGIN;

DROP TRIGGER user_dismissed_track_actions_track_action_id_immutable_tg ON dashboard_public.user_dismissed_track_actions;


COMMIT;
